Repository Squad-1-React-Codenation/Fashionista, pull requests merged in 2020-06, with the labels that each got.

#28 Configura API
  .eslintrc.yml
  src/index.tsx
  src/pages/Home/index.tsx
  src/pages/__tests__/home.test.tsx
  src/routes.tsx
  src/services/__mocks__/productAPI.ts
  src/services/__tests__/productAPI.test.ts
  src/services/index.tsx
  src/services/productAPI.ts
  src/services/types.d.ts
Labels: sig/backend

#27 Corrige Erros do Prettier
  src/styles/main.scss
Labels: sig/qa

#31 Implementa Header
  src/components/base/buttons/index.tsx
  src/components/modules/header/index.tsx
  src/index.tsx
  src/styles/abstracts/_variables.scss
  src/styles/base/_container.scss
  src/styles/components/_button.scss
  src/styles/components/_header.scss
  src/styles/main.scss
Labels: status/wip

#26 Criacao do logo e header com img e estilos temporarios
  package.json
  public/logoundefined.png
  src/components/base/logo/index.tsx
  src/components/modules/header/index.tsx
Labels: kind/feature

#29 create card list home
  src/components/modules/card/index.tsx
  src/pages/Home/index.tsx
  src/styles/abstracts/_reset.scss
  src/styles/abstracts/_variables.scss
  src/styles/components/_card.scss
  src/styles/main.scss
Labels: kind/feature

#53 Adicionando favicon e logo
  public/favicon.ico
  public/favicon.png
  public/index.html
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/components/base/logo/index.tsx
  src/pages/Home/index.tsx
Labels: pts/1

#56 Cria página not found
  .eslintrc.yml
  netlify.toml
  package.json
  src/assets/page-not-found.png
  src/components/base/iconsocial/index.tsx
  src/components/base/logo/index.tsx
  src/components/modules/footer/index.tsx
  src/components/modules/modalCard/index.tsx
  src/config/locales/en/translation.json
  src/config/locales/es/translation.json
  src/config/locales/ptBR/translation.json
  src/pages/Home/index.tsx
  src/pages/NotFound/index.tsx
  src/routes.tsx
  src/styles/main.scss
  src/styles/pages/_notFound.scss
  yarn.lock
Labels: pts/2

#66 Atualiza dependencias e scripts
  netlify.toml
  package.json
  src/pages/__tests__/home.test.tsx
  yarn.lock
Labels: sig/qa
